services:
  postgres:
    image: postgres:14.5
    container_name: soa
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=soa
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"